# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_for_images.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import cv2
import time

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QFileDialog, QTableWidgetItem
from threading import Thread

from src.IntersectionDetector import IntersectionDetector


class MainWindow(QMainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.filenames = None
        self.detected = None
        self.table = {
            "filename": [],
            "intersect": [],
            "%": []
        }
        self.cur_image_indx = 0
        self.detector = IntersectionDetector()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("self")
        self.resize(799, 600)
        self.setWindowTitle("MainWindow")

        self.setObjectName("self")
        self.resize(788, 754)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_image = QtWidgets.QLabel(self.widget)
        self.label_image.setMinimumSize(QtCore.QSize(500, 400))
        self.label_image.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_image.setObjectName("label_image")
        self.verticalLayout.addWidget(self.label_image)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_openFile = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_openFile.setObjectName("pushButton_openFile")
        self.horizontalLayout_2.addWidget(self.pushButton_openFile)
        self.pushButton_Prev = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_Prev.setObjectName("pushButton_Prev")
        self.horizontalLayout_2.addWidget(self.pushButton_Prev)
        self.pushButton_Next = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_Next.setObjectName("pushButton_Next")
        self.horizontalLayout_2.addWidget(self.pushButton_Next)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.widget_2)
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setObjectName("tableWidget")

        self.tableWidget.setColumnCount(3)
        self.tableWidget.setHorizontalHeaderLabels(("filname", "intersect", "%"))
        self.tableWidget.setMinimumSize(761, 193)
        table_width = self.tableWidget.size().width()
        self.tableWidget.setColumnWidth(0, table_width // 2)
        self.tableWidget.setColumnWidth(1, table_width // 4)
        self.tableWidget.setColumnWidth(2, table_width // 4)

        self.verticalLayout.addWidget(self.tableWidget)
        self.pushButton_saveCSV = QtWidgets.QPushButton(self.widget)
        self.pushButton_saveCSV.setObjectName("pushButton_saveCSV")
        self.verticalLayout.addWidget(self.pushButton_saveCSV)
        self.horizontalLayout.addWidget(self.widget)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 788, 21))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.label_image.setText("IMAGE")
        self.pushButton_openFile.setText("Open file")
        self.pushButton_Prev.setText("Пред.")
        self.pushButton_Next.setText("След.")
        self.pushButton_saveCSV.setText("Сохранить CSV-файл")


        QtCore.QMetaObject.connectSlotsByName(self)
        self.buttons()

    
    def buttons(self):
        # Выбор пункта из левого меню
        self.pushButton_openFile.clicked.connect(self.browse_image)
        self.pushButton_Next.clicked.connect(self.next_image)
        self.pushButton_Prev.clicked.connect(self.prev_image)
        self.pushButton_saveCSV.clicked.connect(self.saveCSV)


    def saveCSV(self):
        import pandas as pd

        df = pd.DataFrame(self.table)
        df.to_csv('results.csv')


    def convert_cv_qt(self, cv_img):
        """Convert from an opencv image to QPixmap"""
        rgb_image = cv2.cvtColor(cv_img, cv2.COLOR_BGR2RGB)
        h, w, ch = rgb_image.shape
        bytes_per_line = ch * w
        convert_to_Qt_format = QtGui.QImage(rgb_image.data, w, h, bytes_per_line, QtGui.QImage.Format_RGB888)
        p = convert_to_Qt_format.scaled(
            self.label_image.size().width(), 
            self.label_image.size().height(), 
            QtCore.Qt.KeepAspectRatio
            )
        
        return QtGui.QPixmap.fromImage(p)


    def reset_table(self):
        self.table = {
            "filename": [],
            "intersect": [],
            "%": []
        }


    def add_row_to_table(self, filname, intersect, procent):
        rowCount = self.tableWidget.rowCount()
        self.tableWidget.insertRow(rowCount)
        self.tableWidget.setItem(rowCount, 0, QTableWidgetItem(filname))
        self.tableWidget.setItem(rowCount, 1, QTableWidgetItem(str(intersect)))
        self.tableWidget.setItem(rowCount, 2, QTableWidgetItem(str(procent)))

        self.table["filename"].append(filname)
        self.table["intersect"].append(intersect)
        self.table["%"].append(procent)


    def detect_other_images(self):
        for i in range(1, len(self.filenames)):
            self.detector.set_image_path(
                self.filenames[i]
            )
            intersections = self.detector.calculate_intersections(False)
            self.detected[i] = QtGui.QPixmap(self.convert_cv_qt(self.detector.show_final_image(i+1)))

            self.add_row_to_table(
                self.filenames[i],
                [i > 15 for i in intersections],
                [round(i, 2) for i in intersections]
            )

    def start_detect_other_images(self):
        detect_other_pics = Thread(target=self.detect_other_images)
        detect_other_pics.start()
            
    
    def browse_image(self):
        files, _ = QFileDialog.getOpenFileNames(self, 'Open Image', '', 'Image files (*.jpg *.jpeg *.png)')
        if files: # Если нажали на browse и закрыли оставить прошлые
            self.reset_table()
            self.tableWidget.clear()
            self.tableWidget.setRowCount(0)
            self.filenames = files
            self.detected = [None for _ in range(len(self.filenames))]

            if self.filenames:
                self.detector.set_image_path(
                    self.filenames[0]
                )
                # Отобразить первую картинку
                intersections = self.detector.calculate_intersections(False)
                label_pic = QtGui.QPixmap(self.convert_cv_qt(self.detector.show_final_image(1)))
                self.label_image.setPixmap(label_pic)
                self.detected[0] = label_pic

                self.add_row_to_table(
                    self.filenames[0],
                    [i > 15 for i in intersections],
                    [round(i, 2) for i in intersections]
                )
                # Запустить поток обработки следующих изоражений
                self.start_detect_other_images()
                self.cur_image_indx = 0
        


    def next_image(self):
        if len(self.filenames) > self.cur_image_indx + 1:
            self.cur_image_indx += 1
            while not self.detected[self.cur_image_indx]:
                time.sleep(0.1)
            self.label_image.setPixmap(self.detected[self.cur_image_indx])


    def prev_image(self):
        if self.cur_image_indx > 0:
            self.cur_image_indx -= 1
            while not self.detected[self.cur_image_indx]:
                time.sleep(0.1)
            self.label_image.setPixmap(self.detected[self.cur_image_indx])

    


if __name__ == "__main__":
    

    app = QtWidgets.QApplication(sys.argv)
    win = MainWindow()
    win.show()
    sys.exit(app.exec_())

