# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_for_images.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(788, 754)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_image = QtWidgets.QLabel(self.widget)
        self.label_image.setMinimumSize(QtCore.QSize(500, 400))
        self.label_image.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_image.setObjectName("label_image")
        self.verticalLayout.addWidget(self.label_image)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_openFile = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_openFile.setObjectName("pushButton_openFile")
        self.horizontalLayout_2.addWidget(self.pushButton_openFile)
        self.pushButton_Prev = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_Prev.setObjectName("pushButton_Prev")
        self.horizontalLayout_2.addWidget(self.pushButton_Prev)
        self.pushButton_Next = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_Next.setObjectName("pushButton_Next")
        self.horizontalLayout_2.addWidget(self.pushButton_Next)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.widget_2)
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.pushButton_saveCSV = QtWidgets.QPushButton(self.widget)
        self.pushButton_saveCSV.setObjectName("pushButton_saveCSV")
        self.verticalLayout.addWidget(self.pushButton_saveCSV)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 788, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_image.setText(_translate("MainWindow", "IMAGE"))
        self.pushButton_openFile.setText(_translate("MainWindow", "Open file"))
        self.pushButton_Prev.setText(_translate("MainWindow", "Пред."))
        self.pushButton_Next.setText(_translate("MainWindow", "След."))
        self.pushButton_saveCSV.setText(_translate("MainWindow", "Сохранить CSV-файл"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
